name: 'Build PDFs using make'
description: 'Build PDFs and record time'
inputs:
  makefile-arguments:
    description: 'Arguments to be passed to the Makefile'
    required: false
    default: null
outputs:
  time:
    description: 'The time it took to build the PDFs'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ftsrg/document-converter:2022-v20230319'
  credentials:
     username: ${{ github.actor }}
     password: ${{ secrets.github_token }}
  args:
    - ${{ inputs.makefile-arguments }}
