# action.yml
name: 'Build PDFs using make'
description: 'Build PDFs and record time'
outputs:
  time: # id of output
    description: 'The time it took to build the PDFs'
runs:
  using: 'docker'
  image: 'docker://ftsrg/remo'
