name: 'Build PDFs using make'
description: 'Build PDFs and record time'
inputs:
  makefile-arguments:
    description: 'Arguments to be passed to the Makefile'
    required: false
    default: null
outputs:
  time:
    description: 'The time it took to build the PDFs'
runs:
  using: 'docker'
  image: 'docker://ftsrg/document-converter:2020-v20220329'
  args:
    - ${{ inputs.makefile-arguments }}
