name: 'Build PDFs using make'
description: 'Build PDFs and record time'
inputs:
  makefile-arguments:
    description: 'Arguments to be passed to the Makefile'
    required: false
    default: null
outputs:
  time:
    description: 'The time it took to build the PDFs'
runs:
  using: 'composite'
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run in Docker
      uses: 'docker://ghcr.io/ftsrg/document-converter:2022-v20230319'
      with:
        args: ${{ inputs.makefile-arguments }}
